flowchart TD
    A[HTML] --> B[HEAD]
    A --> C[BODY]
    
    B --> B1[META]
    B --> B2[TITLE]
    B --> B3[CSS]
    
    C --> C1[TITLE]
    C --> C2[CARD]
    
    C2 --> D1[AVATAR]
    C2 --> D2[NAME]
    C2 --> D3[JOB]
    C2 --> D4[DESC]
    C2 --> D5[STATS]
    C2 --> D6[SOCIAL]
    
    D5 --> E1[FOLLOWERS]
    D5 --> E2[FOLLOWING]
    D5 --> E3[PROJECTS]
    
    D6 --> F1[GITHUB]
    D6 --> F2[LINKEDIN]
    D6 --> F3[EMAIL]
    D6 --> F4[TWITTER]